import { delay } from "@/utils/utils";
import { v4 as uuid } from "uuid";
export interface Book {
  id: string;
  price: number;
  name?: string;
  description?: string;
  cover?: string;
  covers?: string[];
  comments: {
    userId: string;
    comment: string;
    id: string;
  }[];
  languages: string[];
}

const booksDB: Book[] = [
  {
    id: "OL30906747W",
    price: 13.99,
    name: "Core Python Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/13192647-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/13192647-L.jpg"],
    comments: [],
    languages: ["python"],
  },
  {
    id: "OL12409294W",
    price: 17.99,
    name: "Core Python programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/7972455-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/10297243-L.jpg",
      "https://covers.openlibrary.org/b/id/7972455-L.jpg",
    ],
    comments: [],
    languages: ["python"],
  },
  {
    id: "OL19547345W",
    price: 34.99,
    name: "Black Hat Python",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8513526-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/13776056-L.jpg",
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/8513526-L.jpg",
      "https://covers.openlibrary.org/b/id/12784724-L.jpg",
      "https://covers.openlibrary.org/b/id/15094720-L.jpg",
    ],
    comments: [],
    languages: ["python"],
  },
  {
    id: "OL20212390W",
    price: 10.99,
    name: "Python",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8863687-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/8863687-L.jpg",
    ],
    comments: [],
    languages: ["python"],
  },
  {
    id: "OL25171735W",
    price: 35.99,
    name: "Python Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/11978097-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/11978097-L.jpg"],
    comments: [],
    languages: ["python"],
  },
  {
    id: "OL24567802W",
    price: 17.99,
    name: "Python Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/11218742-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/11218742-L.jpg"],
    comments: [],
    languages: ["python"],
  },
  {
    id: "OL6037340W",
    price: 11.99,
    name: "Python programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/935554-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/935554-L.jpg"],
    comments: [],
    languages: ["python"],
  },
  {
    id: "OL27103303W",
    price: 21.99,
    name: "Python Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/12587933-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/12587933-L.jpg",
    ],
    comments: [],
    languages: ["python"],
  },
  {
    id: "OL5830811W",
    price: 41.99,
    name: "Python programming in context",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/5358324-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/10194187-L.jpg",
      "https://covers.openlibrary.org/b/id/5358324-L.jpg",
    ],
    comments: [],
    languages: ["python"],
  },
  {
    id: "OL2784126W",
    price: 34.99,
    name: "Programming Python",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/805644-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/6667686-L.jpg",
      "https://covers.openlibrary.org/b/id/805644-L.jpg",
      "https://covers.openlibrary.org/b/id/388483-L.jpg",
      "https://covers.openlibrary.org/b/id/805643-L.jpg",
      "https://covers.openlibrary.org/b/id/6983580-L.jpg",
      "https://covers.openlibrary.org/b/id/389105-L.jpg",
    ],
    comments: [],
    languages: ["python"],
  },
  {
    id: "OL2784125W",
    price: 43.99,
    name: "Learning Python",
    description:
      "Describes the features of the Python 2.5 programming language, covering such topics as types and operations, statements and syntax, functions, modules, classes and OOP, and exceptions and tools.",
    cover: "https://covers.openlibrary.org/b/id/1312568-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/8686134-L.jpg",
      "https://covers.openlibrary.org/b/id/14618670-L.jpg",
      "https://covers.openlibrary.org/b/id/1312568-L.jpg",
      "https://covers.openlibrary.org/b/id/388619-L.jpg",
      "https://covers.openlibrary.org/b/id/15101728-L.jpg",
      "https://covers.openlibrary.org/b/id/12746191-L.jpg",
      "https://covers.openlibrary.org/b/id/6684175-L.jpg",
      "https://covers.openlibrary.org/b/id/6283352-L.jpg",
      "https://covers.openlibrary.org/b/id/805795-L.jpg",
      "https://covers.openlibrary.org/b/id/15147873-L.jpg",
      "https://covers.openlibrary.org/b/id/388620-L.jpg",
    ],
    comments: [],
    languages: ["python"],
  },
  {
    id: "OL17755203W",
    price: 40.99,
    name: "Python Programming For Beginners",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8036365-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/8036365-L.jpg"],
    comments: [],
    languages: ["python"],
  },
  {
    id: "OL4617640W",
    price: 48.99,
    name: "The C Programming Language",
    description:
      "Very well known, classic introduction to the C Programming Language. Both a text for learning, a reference, and, to some, the definition of proper C language features and use.",
    cover: "https://covers.openlibrary.org/b/id/6684943-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/1007697-L.jpg",
      "https://covers.openlibrary.org/b/id/10389817-L.jpg",
      "https://covers.openlibrary.org/b/id/1007688-L.jpg",
      "https://covers.openlibrary.org/b/id/13078972-L.jpg",
      "https://covers.openlibrary.org/b/id/5732572-L.jpg",
      "https://covers.openlibrary.org/b/id/10557818-L.jpg",
      "https://covers.openlibrary.org/b/id/86184-L.jpg",
      "https://covers.openlibrary.org/b/id/12592774-L.jpg",
      "https://covers.openlibrary.org/b/id/4926915-L.jpg",
      "https://covers.openlibrary.org/b/id/6921000-L.jpg",
      "https://covers.openlibrary.org/b/id/6672396-L.jpg",
      "https://covers.openlibrary.org/b/id/8593506-L.jpg",
      "https://covers.openlibrary.org/b/id/6684943-L.jpg",
      "https://covers.openlibrary.org/b/id/86185-L.jpg",
      "https://covers.openlibrary.org/b/id/13904404-L.jpg",
      "https://covers.openlibrary.org/b/id/86178-L.jpg",
      "https://covers.openlibrary.org/b/id/13087690-L.jpg",
      "https://covers.openlibrary.org/b/id/14089111-L.jpg",
      "https://covers.openlibrary.org/b/id/11506009-L.jpg",
      "https://covers.openlibrary.org/b/id/8740835-L.jpg",
      "https://covers.openlibrary.org/b/id/972278-L.jpg",
    ],
    comments: [],
    languages: ["cpp"],
  },
  {
    id: "OL53184W",
    price: 44.99,
    name: "The cpp programming language",
    description:
      "The cpp Programming tome, written by the father of cpp himself, Bjarne Stroustrup.  The premier book on the subject of cpp Programming.",
    cover: "https://covers.openlibrary.org/b/id/136583-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/8681288-L.jpg",
      "https://covers.openlibrary.org/b/id/8553889-L.jpg",
      "https://covers.openlibrary.org/b/id/13841567-L.jpg",
      "https://covers.openlibrary.org/b/id/7912044-L.jpg",
      "https://covers.openlibrary.org/b/id/135114-L.jpg",
      "https://covers.openlibrary.org/b/id/9672472-L.jpg",
      "https://covers.openlibrary.org/b/id/136583-L.jpg",
      "https://covers.openlibrary.org/b/id/6621633-L.jpg",
      "https://covers.openlibrary.org/b/id/8526272-L.jpg",
      "https://covers.openlibrary.org/b/id/8638220-L.jpg",
      "https://covers.openlibrary.org/b/id/135813-L.jpg",
      "https://covers.openlibrary.org/b/id/14542464-L.jpg",
      "https://covers.openlibrary.org/b/id/5732573-L.jpg",
      "https://covers.openlibrary.org/b/id/6754889-L.jpg",
    ],
    comments: [],
    languages: ["cpp"],
  },
  {
    id: "OL3233592W",
    price: 37.99,
    name: "C programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/252635-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/9888903-L.jpg",
      "https://covers.openlibrary.org/b/id/252635-L.jpg",
    ],
    comments: [],
    languages: ["cpp"],
  },
  {
    id: "OL17734885W",
    price: 45.99,
    name: "Let us C",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8013973-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/15114881-L.jpg",
      "https://covers.openlibrary.org/b/id/8013973-L.jpg",
    ],
    comments: [],
    languages: ["cpp"],
  },
  {
    id: "OL8221396W",
    price: 24.99,
    name: "cpp Programming",
    description:
      "Written for the modern programmer, this innovative text does not rely heavily on math and engineering-orientated skills, but focuses on the nature and obvious advantages of cpp as a language.",
    cover: "https://covers.openlibrary.org/b/id/762861-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/762861-L.jpg",
      "https://covers.openlibrary.org/b/id/762862-L.jpg",
      "https://covers.openlibrary.org/b/id/395356-L.jpg",
      "https://covers.openlibrary.org/b/id/4640477-L.jpg",
      "https://covers.openlibrary.org/b/id/11108267-L.jpg",
      "https://covers.openlibrary.org/b/id/10603736-L.jpg",
      "https://covers.openlibrary.org/b/id/5162087-L.jpg",
      "https://covers.openlibrary.org/b/id/5162086-L.jpg",
      "https://covers.openlibrary.org/b/id/12665015-L.jpg",
      "https://covers.openlibrary.org/b/id/11611663-L.jpg",
    ],
    comments: [],
    languages: ["cpp"],
  },
  {
    id: "OL2036125W",
    price: 24.99,
    name: "The Waite Group's Turbo C programming for the PC",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/410094-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/13364887-L.jpg"],
    comments: [],
    languages: ["cpp"],
  },
  {
    id: "OL1140109W",
    price: 24.99,
    name: "The Good Earth",
    description:
      "This tells the poignant tale of a Chinese farmer and his family in old agrarian China. The humble Wang Lung glories in the soil he works, nurturing the land as it nurtures him and his family. Nearby, the nobles of the House of Hwang consider themselves above the land and its workers; but they will soon meet their own downfall.\r\n\r\nHard times come upon Wang Lung and his family when flood and drought force them to seek work in the city. The working people riot, breaking into the homes of the rich and forcing them to flee. When Wang Lung shows mercy to one noble and is rewarded, he begins to rise in the world, even as the House of Hwang falls.",
    cover: "https://covers.openlibrary.org/b/id/2626823-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/14971110-L.jpg",
      "https://covers.openlibrary.org/b/id/14471050-L.jpg",
      "https://covers.openlibrary.org/b/id/14971103-L.jpg",
      "https://covers.openlibrary.org/b/id/8236695-L.jpg",
      "https://covers.openlibrary.org/b/id/14945571-L.jpg",
      "https://covers.openlibrary.org/b/id/13533484-L.jpg",
      "https://covers.openlibrary.org/b/id/8609157-L.jpg",
      "https://covers.openlibrary.org/b/id/10020842-L.jpg",
      "https://covers.openlibrary.org/b/id/14971111-L.jpg",
      "https://covers.openlibrary.org/b/id/4650117-L.jpg",
      "https://covers.openlibrary.org/b/id/7271579-L.jpg",
    ],
    comments: [],
    languages: ["cpp"],
  },
  {
    id: "OL17773390W",
    price: 33.99,
    name: "Practical javascript programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/3854378-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/3854378-L.jpg"],
    comments: [],
    languages: ["javascript"],
  },
  {
    id: "OL25632028W",
    price: 45.99,
    name: "javascript Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/14483955-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/14483955-L.jpg"],
    comments: [],
    languages: ["javascript"],
  },
  {
    id: "OL21867740W",
    price: 20.99,
    name: "javascript Programming Pattern",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/13886516-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/13886516-L.jpg"],
    comments: [],
    languages: ["javascript"],
  },

  {
    id: "OL25520448W",
    price: 32.99,
    name: "javascript",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/13789638-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/13789638-L.jpg"],
    comments: [],
    languages: ["javascript"],
  },

  {
    id: "OL15444205W",
    price: 29.99,
    name: "Eloquent javascript",
    description:
      '"*Eloquent javascript* is a book providing an introduction to the javascript programming language and programming in general."',
    cover: "https://covers.openlibrary.org/b/id/7082166-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/14820601-L.jpg",
      "https://covers.openlibrary.org/b/id/7199153-L.jpg",
      "https://covers.openlibrary.org/b/id/8644134-L.jpg",
      "https://covers.openlibrary.org/b/id/12995869-L.jpg",
      "https://covers.openlibrary.org/b/id/8508178-L.jpg",
      "https://covers.openlibrary.org/b/id/10601909-L.jpg",
      "https://covers.openlibrary.org/b/id/8513405-L.jpg",
    ],
    comments: [],
    languages: ["javascript"],
  },

  {
    id: "OL2692465W",
    price: 12.99,
    name: "Learn advanced javascript programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/1874138-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/1874138-L.jpg"],
    comments: [],
    languages: ["javascript"],
  },
  {
    id: "OL1643770W",
    price: 22.99,
    name: "javascript",
    description:
      "javascript is a powerful, object-based scripting language; javascript programs can be embedded directly into HTML web pages. When combined with the Document Object Model (DOM) defined by a web browser, javascript allows you to create Dynamic HTML (DHTML) content and interactive client-side web applications. javascript syntax is based on the popular programming languages C, cpp, and java, which makes it familiar and easy to learn for experienced programmers. At the same time, javascript is an interpreted scripting language, providing a flexible, forgiving environment in which new programmers can learn.\r\n\r\n*javascript: The Definitive Guide* provides a thorough description of the core javascript language and both the legacy and standard DOMs implemented in web browsers. The book includes sophisticated examples that show you how to handle common tasks such as validating form data, working with cookies, and creating portable DHTML animations. The book also contains detailed reference sections that cover the core javascript API, the legacy client-side API, and the W3C standard DOM API, documenting every javascript object, method, property, constructor, constant, function, and event handler in those APIs.\r\n\r\nThis fourth edition of the bestselling javascript book has been carefully updated to cover javascript 1.5 (ECMAScript Version 3). The book also provides complete coverage of the W3C DOM standard (Level 1 and Level 2), while retaining material on the legacy Level 0 DOM for backward compatibility.\r\n\r\n*javascript: The Definitive Guide* is a complete programmer's guide and reference manual for javascript. It is particularly useful for developers working with the latest standards-compliant web browsers, such as Internet Explorer 6, Netscape 6, and Mozilla. HTML authors can learn how to use javascript to build dynamic web pages. Experienced programmers can quickly find the information they need to start writing sophisticated javascript programs. This book is an indispensable reference for all javascript programmers, regardless of experience level.\r\n\r\n----------\r\n*Description from the Fourth Edition (2007, O'Reilly Media)*\r\n\r\n<h2>Printing History</h2>\r\n<dl> \r\n<dt>August 1996</dt>\r\n<dd>Beta Edition.</dd>\r\n<dt>January 1997</dt>\r\n<dd>Second Edition.</dd> \r\n<dt>June 1998</dt>\r\n<dd>Third Edition.</dd> \r\n<dt>January 2002</dt>\r\n<dd>Fourth Edition.</dd> \r\n</dl>",
    cover: "https://covers.openlibrary.org/b/id/10737959-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/805641-L.jpg",
      "https://covers.openlibrary.org/b/id/14488181-L.jpg",
      "https://covers.openlibrary.org/b/id/6519345-L.jpg",
      "https://covers.openlibrary.org/b/id/14562317-L.jpg",
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/10229384-L.jpg",
      "https://covers.openlibrary.org/b/id/10737969-L.jpg",
      "https://covers.openlibrary.org/b/id/15087914-L.jpg",
      "https://covers.openlibrary.org/b/id/988222-L.jpg",
      "https://covers.openlibrary.org/b/id/10737959-L.jpg",
      "https://covers.openlibrary.org/b/id/10738025-L.jpg",
      "https://covers.openlibrary.org/b/id/805759-L.jpg",
      "https://covers.openlibrary.org/b/id/13955143-L.jpg",
      "https://covers.openlibrary.org/b/id/10738098-L.jpg",
      "https://covers.openlibrary.org/b/id/13955144-L.jpg",
      "https://covers.openlibrary.org/b/id/388464-L.jpg",
      "https://covers.openlibrary.org/b/id/10738063-L.jpg",
    ],
    comments: [],
    languages: ["javascript"],
  },
  {
    id: "OL8221266W",
    price: 26.99,
    name: "HTML & javascript",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/365269-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/365269-L.jpg",
      "https://covers.openlibrary.org/b/id/13091091-L.jpg",
    ],
    comments: [],
    languages: ["javascript"],
  },
  {
    id: "OL24807285W",
    price: 27.99,
    name: "javascript",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/11575841-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/11575841-L.jpg"],
    comments: [],
    languages: ["javascript"],
  },
  {
    id: "OL1820616W",
    price: 12.99,
    name: "Java and javascript programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/1100750-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/1100750-L.jpg"],
    comments: [],
    languages: ["javascript"],
  },
  {
    id: "OL13614569W",
    price: 40.99,
    name: "The javascript programming language",
    description:
      '"The javascript Programming Language provides a brief introduction to the javascript language that is now an important component of every programmer\'s tool box. This helpful guide offers an overview of javascript to students interested in pursuing advanced programming skills and delving into web development." "Clear and concise, The javascript Programming Language is an excellent primer to this popular dynamic language and is ideal for use on its own or when coupled with one of Jones and Bartlett\'s outstanding introductory computer science texts"--Book jacket.',
    cover: "https://covers.openlibrary.org/b/id/12191848-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/12191848-L.jpg"],
    comments: [],
    languages: ["javascript"],
  },

  {
    id: "OL19546617W",
    price: 41.99,
    name: "javascript: Beginners Guide on javascript Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8512669-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/8512669-L.jpg"],
    comments: [],
    languages: ["javascript"],
  },

  {
    id: "OL114676W",
    price: 10.99,
    name: "Introduction to Java Programming",
    description:
      "For courses in Java - Introduction to Programming and Object-Oriented Programming, this fifth edition is revised and expanded to include more extensive coverage of advanced Java topics. Early chapters guide students through simple examples and exercises.Subsequent chapters progressively present Java programming in detail.",
    cover: "https://covers.openlibrary.org/b/id/85920-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/85920-L.jpg",
      "https://covers.openlibrary.org/b/id/13097152-L.jpg",
      "https://covers.openlibrary.org/b/id/82465-L.jpg",
      "https://covers.openlibrary.org/b/id/841053-L.jpg",
      "https://covers.openlibrary.org/b/id/89462-L.jpg",
      "https://covers.openlibrary.org/b/id/82464-L.jpg",
      "https://covers.openlibrary.org/b/id/89461-L.jpg",
    ],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL3503668W",
    price: 27.99,
    name: "Java Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/5406811-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/4813741-L.jpg",
      "https://covers.openlibrary.org/b/id/4640811-L.jpg",
      "https://covers.openlibrary.org/b/id/14847889-L.jpg",
      "https://covers.openlibrary.org/b/id/5406811-L.jpg",
    ],
    comments: [],
    languages: ["java"],
  },

  {
    id: "OL6223299W",
    price: 20.99,
    name: "Effective Java",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/1176573-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/2334826-L.jpg",
      "https://covers.openlibrary.org/b/id/134335-L.jpg",
      "https://covers.openlibrary.org/b/id/8509606-L.jpg",
      "https://covers.openlibrary.org/b/id/12420356-L.jpg",
      "https://covers.openlibrary.org/b/id/7429009-L.jpg",
      "https://covers.openlibrary.org/b/id/9348726-L.jpg",
      "https://covers.openlibrary.org/b/id/9911458-L.jpg",
      "https://covers.openlibrary.org/b/id/1176573-L.jpg",
    ],
    comments: [],
    languages: ["java"],
  },

  {
    id: "OL16988753W",
    price: 20.99,
    name: "Java programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/9430172-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/9430172-L.jpg"],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL29571480W",
    price: 36.99,
    name: "Java Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/13164331-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/13164331-L.jpg"],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL449055W",
    price: 36.99,
    name: "Big Java",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/1239523-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/1239523-L.jpg",
      "https://covers.openlibrary.org/b/id/304392-L.jpg",
      "https://covers.openlibrary.org/b/id/6382989-L.jpg",
      "https://covers.openlibrary.org/b/id/306377-L.jpg",
    ],
    comments: [],
    languages: ["java"],
  },

  {
    id: "OL8492268W",
    price: 48.99,
    name: "Java Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/506676-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/506676-L.jpg"],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL3233590W",
    price: 15.99,
    name: "Java Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/252868-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/252869-L.jpg",
      "https://covers.openlibrary.org/b/id/252868-L.jpg",
    ],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL22705232W",
    price: 48.99,
    name: "Programming with Java",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/10487733-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/14859622-L.jpg",
      "https://covers.openlibrary.org/b/id/10487733-L.jpg",
      "https://covers.openlibrary.org/b/id/10557761-L.jpg",
      "https://covers.openlibrary.org/b/id/13707897-L.jpg",
      "https://covers.openlibrary.org/b/id/10599410-L.jpg",
      "https://covers.openlibrary.org/b/id/10557760-L.jpg",
    ],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL11987899W",
    price: 27.99,
    name: "Java programming",
    description:
      '"This book was written for cpp programmers to learn the Java programming language using JDK 1.1. You can leverage your cpp skills to quickly develop Java skills to at least the level of Certified Java Programmer as defined by the Sun certification program.".\n\n"This book moves from the basics of the Java language to the essential and powerful programming techniques supported by the Java language, including extending existing classes, implementing interfaces, exception handling, multithreading, cloning objects, run-time type information, and advanced language constructs such as inner classes. This book gives overviews of the packages provided by the Java platform.\n\nThe classes in these packages support stream I/O and random-access file I/O, networking, collection classes, programming graphical user interfaces for applications, creating applets, and internationalizing programs. A chapter on JavaBeans - reusable software components that can be input directly into an ever-growing number of rapid application development (RAD) tools - is also included."--BOOK JACKET.',
    cover: "https://covers.openlibrary.org/b/id/1421552-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/9830071-L.jpg",
      "https://covers.openlibrary.org/b/id/1421552-L.jpg",
    ],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL23868245W",
    price: 23.99,
    name: "Java program design",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/5005860-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/5005860-L.jpg"],
    comments: [],
    languages: ["java"],
  },

  {
    id: "OL15959929W",
    price: 23.99,
    name: "Introduction to JAVA programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/9435785-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/9435785-L.jpg"],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL16961757W",
    price: 10.99,
    name: "Introduction to JAVA programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/9537991-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/9537991-L.jpg"],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL16509491W",
    price: 25.99,
    name: "Introduction to Java programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8665105-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/8665105-L.jpg"],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL5974397W",
    price: 48.99,
    name: "Java programming with Oracle JDBC",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/388485-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/388485-L.jpg"],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL2863751W",
    price: 49.99,
    name: "KickAss Java Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/2083449-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/2083449-L.jpg",
      "https://covers.openlibrary.org/b/id/2083448-L.jpg",
    ],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL16342737W",
    price: 26.99,
    name: "Java programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/13162223-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/13162223-L.jpg"],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL2734879W",
    price: 29.99,
    name: "The Java programming language",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/135609-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/135872-L.jpg",
      "https://covers.openlibrary.org/b/id/134336-L.jpg",
      "https://covers.openlibrary.org/b/id/135609-L.jpg",
      "https://covers.openlibrary.org/b/id/8359411-L.jpg",
    ],
    comments: [],
    languages: ["java"],
  },
  {
    id: "OL18996549W",
    price: 46.99,
    name: "Java Program Design",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/64961-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/64960-L.jpg",
      "https://covers.openlibrary.org/b/id/64961-L.jpg",
    ],
    comments: [],
    languages: ["java"],
  },
];

export const getBooks = async () => {
  const dbToken = process.env.SIMULATED_DB_TOKEN;
  /*  if (!dbToken) {
    console.warn(
      "⚠️ Advertencia: No se encontró SIMULATED_DB_TOKEN en .env.local. Usando conexión no segura.",
    );
  } else {
    console.log(
      `🔒 [Server] Autenticando con DB simulada usando token: ${dbToken.substring(0, 10)}...`,
    );
  } */

  await delay(200);
  return booksDB;
};

export const addBook = async (book: Book) => {
  await delay(200);
  booksDB.push(book);
};

export const getBook = async (bookId: string) => {
  await delay(200);
  return booksDB.find((item) => item.id == bookId) ?? null;
};

export const addComment = async (
  comment: string,
  userId: string,
  bookId: string,
) => {
  await delay(200);
  const book = booksDB.find((item) => item.id == bookId) ?? null;
  if (!book) return;
  book.comments.unshift({ userId, comment, id: uuid() });
};
