import { delay } from "@/utils/utils";

export interface Book {
  id: string;
  price: number;
  name?: string;
  description?: string;
  cover?: string;
  covers?: string[];
  comments: {
    userId: string;
    message: string;
  }[];
}

const booksDB: Book[] = [
  {
    id: "OL30906747W",
    price: 13.99,
    name: "Core Python Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/13192647-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/13192647-L.jpg"],
    comments: [],
  },
  {
    id: "OL12409294W",
    price: 17.99,
    name: "Core Python programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/7972455-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/10297243-L.jpg",
      "https://covers.openlibrary.org/b/id/7972455-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL19547345W",
    price: 34.99,
    name: "Black Hat Python",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8513526-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/13776056-L.jpg",
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/8513526-L.jpg",
      "https://covers.openlibrary.org/b/id/12784724-L.jpg",
      "https://covers.openlibrary.org/b/id/15094720-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL20212390W",
    price: 10.99,
    name: "Python",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8863687-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/8863687-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL25171735W",
    price: 35.99,
    name: "Python Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/11978097-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/11978097-L.jpg"],
    comments: [],
  },
  {
    id: "OL24567802W",
    price: 17.99,
    name: "Python Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/11218742-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/11218742-L.jpg"],
    comments: [],
  },
  {
    id: "OL6037340W",
    price: 11.99,
    name: "Python programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/935554-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/935554-L.jpg"],
    comments: [],
  },
  {
    id: "OL27103303W",
    price: 21.99,
    name: "Python Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/12587933-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/12587933-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL5830811W",
    price: 41.99,
    name: "Python programming in context",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/5358324-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/10194187-L.jpg",
      "https://covers.openlibrary.org/b/id/5358324-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL2784126W",
    price: 34.99,
    name: "Programming Python",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/805644-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/6667686-L.jpg",
      "https://covers.openlibrary.org/b/id/805644-L.jpg",
      "https://covers.openlibrary.org/b/id/388483-L.jpg",
      "https://covers.openlibrary.org/b/id/805643-L.jpg",
      "https://covers.openlibrary.org/b/id/6983580-L.jpg",
      "https://covers.openlibrary.org/b/id/389105-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL2784125W",
    price: 43.99,
    name: "Learning Python",
    description:
      "Describes the features of the Python 2.5 programming language, covering such topics as types and operations, statements and syntax, functions, modules, classes and OOP, and exceptions and tools.",
    cover: "https://covers.openlibrary.org/b/id/1312568-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/8686134-L.jpg",
      "https://covers.openlibrary.org/b/id/14618670-L.jpg",
      "https://covers.openlibrary.org/b/id/1312568-L.jpg",
      "https://covers.openlibrary.org/b/id/388619-L.jpg",
      "https://covers.openlibrary.org/b/id/15101728-L.jpg",
      "https://covers.openlibrary.org/b/id/12746191-L.jpg",
      "https://covers.openlibrary.org/b/id/6684175-L.jpg",
      "https://covers.openlibrary.org/b/id/6283352-L.jpg",
      "https://covers.openlibrary.org/b/id/805795-L.jpg",
      "https://covers.openlibrary.org/b/id/15147873-L.jpg",
      "https://covers.openlibrary.org/b/id/388620-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL17755203W",
    price: 40.99,
    name: "Python Programming For Beginners",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8036365-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/8036365-L.jpg"],
    comments: [],
  },
  {
    id: "OL4617640W",
    price: 48.99,
    name: "The C Programming Language",
    description:
      "Very well known, classic introduction to the C Programming Language. Both a text for learning, a reference, and, to some, the definition of proper C language features and use.",
    cover: "https://covers.openlibrary.org/b/id/6684943-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/1007697-L.jpg",
      "https://covers.openlibrary.org/b/id/10389817-L.jpg",
      "https://covers.openlibrary.org/b/id/1007688-L.jpg",
      "https://covers.openlibrary.org/b/id/13078972-L.jpg",
      "https://covers.openlibrary.org/b/id/5732572-L.jpg",
      "https://covers.openlibrary.org/b/id/10557818-L.jpg",
      "https://covers.openlibrary.org/b/id/86184-L.jpg",
      "https://covers.openlibrary.org/b/id/12592774-L.jpg",
      "https://covers.openlibrary.org/b/id/4926915-L.jpg",
      "https://covers.openlibrary.org/b/id/6921000-L.jpg",
      "https://covers.openlibrary.org/b/id/6672396-L.jpg",
      "https://covers.openlibrary.org/b/id/8593506-L.jpg",
      "https://covers.openlibrary.org/b/id/6684943-L.jpg",
      "https://covers.openlibrary.org/b/id/86185-L.jpg",
      "https://covers.openlibrary.org/b/id/13904404-L.jpg",
      "https://covers.openlibrary.org/b/id/86178-L.jpg",
      "https://covers.openlibrary.org/b/id/13087690-L.jpg",
      "https://covers.openlibrary.org/b/id/14089111-L.jpg",
      "https://covers.openlibrary.org/b/id/11506009-L.jpg",
      "https://covers.openlibrary.org/b/id/8740835-L.jpg",
      "https://covers.openlibrary.org/b/id/972278-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL53184W",
    price: 44.99,
    name: "The C++ programming language",
    description:
      "The C++ Programming tome, written by the father of C++ himself, Bjarne Stroustrup.  The premier book on the subject of C++ Programming.",
    cover: "https://covers.openlibrary.org/b/id/136583-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/8681288-L.jpg",
      "https://covers.openlibrary.org/b/id/8553889-L.jpg",
      "https://covers.openlibrary.org/b/id/13841567-L.jpg",
      "https://covers.openlibrary.org/b/id/7912044-L.jpg",
      "https://covers.openlibrary.org/b/id/135114-L.jpg",
      "https://covers.openlibrary.org/b/id/9672472-L.jpg",
      "https://covers.openlibrary.org/b/id/136583-L.jpg",
      "https://covers.openlibrary.org/b/id/6621633-L.jpg",
      "https://covers.openlibrary.org/b/id/8526272-L.jpg",
      "https://covers.openlibrary.org/b/id/8638220-L.jpg",
      "https://covers.openlibrary.org/b/id/135813-L.jpg",
      "https://covers.openlibrary.org/b/id/14542464-L.jpg",
      "https://covers.openlibrary.org/b/id/5732573-L.jpg",
      "https://covers.openlibrary.org/b/id/6754889-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL3233592W",
    price: 37.99,
    name: "C programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/252635-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/9888903-L.jpg",
      "https://covers.openlibrary.org/b/id/252635-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL17734885W",
    price: 45.99,
    name: "Let us C",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8013973-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/15114881-L.jpg",
      "https://covers.openlibrary.org/b/id/8013973-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL71132W",
    price: 35.99,
    name: "The Voyage of the Dawn Treader",
    description:
      'Lucy, Edmund, and their cousin travel back to Narnia through a painting where they board a ship named "The Dawn Treader." They find King Caspian and a mouse on the ship and they find mystical creatures and go on a mission that will decide Narnia\'s fate!',
    cover: "https://covers.openlibrary.org/b/id/9184719-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/6667506-L.jpg",
      "https://covers.openlibrary.org/b/id/14653661-L.jpg",
      "https://covers.openlibrary.org/b/id/9184731-L.jpg",
      "https://covers.openlibrary.org/b/id/10636759-L.jpg",
      "https://covers.openlibrary.org/b/id/10377176-L.jpg",
      "https://covers.openlibrary.org/b/id/1052376-L.jpg",
      "https://covers.openlibrary.org/b/id/8113952-L.jpg",
      "https://covers.openlibrary.org/b/id/10160876-L.jpg",
      "https://covers.openlibrary.org/b/id/229-L.jpg",
      "https://covers.openlibrary.org/b/id/7217-L.jpg",
      "https://covers.openlibrary.org/b/id/8568851-L.jpg",
      "https://covers.openlibrary.org/b/id/36418-L.jpg",
      "https://covers.openlibrary.org/b/id/7218-L.jpg",
      "https://covers.openlibrary.org/b/id/10706408-L.jpg",
      "https://covers.openlibrary.org/b/id/11423770-L.jpg",
      "https://covers.openlibrary.org/b/id/14004382-L.jpg",
      "https://covers.openlibrary.org/b/id/7783239-L.jpg",
      "https://covers.openlibrary.org/b/id/2269427-L.jpg",
      "https://covers.openlibrary.org/b/id/7283595-L.jpg",
      "https://covers.openlibrary.org/b/id/9184722-L.jpg",
      "https://covers.openlibrary.org/b/id/10645839-L.jpg",
      "https://covers.openlibrary.org/b/id/6391873-L.jpg",
      "https://covers.openlibrary.org/b/id/9184719-L.jpg",
      "https://covers.openlibrary.org/b/id/39000-L.jpg",
      "https://covers.openlibrary.org/b/id/13263642-L.jpg",
      "https://covers.openlibrary.org/b/id/9184729-L.jpg",
      "https://covers.openlibrary.org/b/id/11517099-L.jpg",
      "https://covers.openlibrary.org/b/id/13748128-L.jpg",
      "https://covers.openlibrary.org/b/id/10388866-L.jpg",
      "https://covers.openlibrary.org/b/id/10640042-L.jpg",
      "https://covers.openlibrary.org/b/id/9184713-L.jpg",
      "https://covers.openlibrary.org/b/id/697694-L.jpg",
      "https://covers.openlibrary.org/b/id/7355519-L.jpg",
      "https://covers.openlibrary.org/b/id/10615522-L.jpg",
      "https://covers.openlibrary.org/b/id/8686472-L.jpg",
      "https://covers.openlibrary.org/b/id/39001-L.jpg",
      "https://covers.openlibrary.org/b/id/540796-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL8221396W",
    price: 24.99,
    name: "C++ Programming",
    description:
      "Written for the modern programmer, this innovative text does not rely heavily on math and engineering-orientated skills, but focuses on the nature and obvious advantages of C++ as a language.",
    cover: "https://covers.openlibrary.org/b/id/762861-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/762861-L.jpg",
      "https://covers.openlibrary.org/b/id/762862-L.jpg",
      "https://covers.openlibrary.org/b/id/395356-L.jpg",
      "https://covers.openlibrary.org/b/id/4640477-L.jpg",
      "https://covers.openlibrary.org/b/id/11108267-L.jpg",
      "https://covers.openlibrary.org/b/id/10603736-L.jpg",
      "https://covers.openlibrary.org/b/id/5162087-L.jpg",
      "https://covers.openlibrary.org/b/id/5162086-L.jpg",
      "https://covers.openlibrary.org/b/id/12665015-L.jpg",
      "https://covers.openlibrary.org/b/id/11611663-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL2036125W",
    price: 24.99,
    name: "The Waite Group's Turbo C programming for the PC",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/410094-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/13364887-L.jpg"],
    comments: [],
  },
  {
    id: "OL262460W",
    price: 31.99,
    name: "The Lost World",
    description:
      "Journalist Ed Malone is looking for an adventure, and that's exactly what he finds when he meets the eccentric Professor Challenger - an adventure that leads Malone and his three companions deep into the Amazon jungle, to a lost world where dinosaurs roam free.",
    cover: "https://covers.openlibrary.org/b/id/8231444-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/14702511-L.jpg",
      "https://covers.openlibrary.org/b/id/10916602-L.jpg",
      "https://covers.openlibrary.org/b/id/10605851-L.jpg",
      "https://covers.openlibrary.org/b/id/13770956-L.jpg",
      "https://covers.openlibrary.org/b/id/12819846-L.jpg",
      "https://covers.openlibrary.org/b/id/14857369-L.jpg",
      "https://covers.openlibrary.org/b/id/12373291-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL45089W",
    price: 41.99,
    name: "Robinson Crusoe",
    description:
      "During one of his several adventurous voyages in the 1600's, an Englishman becomes the sole survivor of a shipwreck and lives for nearly thirty years on a deserted island.",
    cover: "https://covers.openlibrary.org/b/id/368541-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/13496017-L.jpg",
      "https://covers.openlibrary.org/b/id/15053785-L.jpg",
      "https://covers.openlibrary.org/b/id/13496016-L.jpg",
      "https://covers.openlibrary.org/b/id/10889632-L.jpg",
      "https://covers.openlibrary.org/b/id/14513680-L.jpg",
      "https://covers.openlibrary.org/b/id/14642548-L.jpg",
      "https://covers.openlibrary.org/b/id/13496019-L.jpg",
      "https://covers.openlibrary.org/b/id/13154819-L.jpg",
      "https://covers.openlibrary.org/b/id/12058628-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL8662242W",
    price: 20.99,
    name: "David Copperfield",
    description:
      "It adds to the charm of this book to remember that it is virtually a picture of the author's own boyhood. It is an excellent picture of the life of a struggling English youth in the middle of the last century. The pictures of Canterbury and London are true pictures and through these pages walk one of Dickens' wonderful processions of characters, quaint and humorous, villainous and tragic. Nobody cares for Dickens heroines, least of all for Dora, but take it all in al, l this book is enjoyed by young people more than any other of the great novelist. After having read this you will wish to read Nicholas Nickleby for its mingling of pathos and humor, Martin Chuzzlewit for its pictures of American life as seen through English eyes, and Pickwick Papers for its crude but boisterous humor.",
    cover: "https://covers.openlibrary.org/b/id/1048892-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/603698-L.jpg",
      "https://covers.openlibrary.org/b/id/12979981-L.jpg",
      "https://covers.openlibrary.org/b/id/13136584-L.jpg",
      "https://covers.openlibrary.org/b/id/9280535-L.jpg",
      "https://covers.openlibrary.org/b/id/6011309-L.jpg",
      "https://covers.openlibrary.org/b/id/15096014-L.jpg",
      "https://covers.openlibrary.org/b/id/3055137-L.jpg",
      "https://covers.openlibrary.org/b/id/13116036-L.jpg",
      "https://covers.openlibrary.org/b/id/6992430-L.jpg",
      "https://covers.openlibrary.org/b/id/417334-L.jpg",
      "https://covers.openlibrary.org/b/id/9282643-L.jpg",
      "https://covers.openlibrary.org/b/id/102974-L.jpg",
      "https://covers.openlibrary.org/b/id/295366-L.jpg",
      "https://covers.openlibrary.org/b/id/2981269-L.jpg",
      "https://covers.openlibrary.org/b/id/2584000-L.jpg",
      "https://covers.openlibrary.org/b/id/15146913-L.jpg",
      "https://covers.openlibrary.org/b/id/9280634-L.jpg",
      "https://covers.openlibrary.org/b/id/2216652-L.jpg",
      "https://covers.openlibrary.org/b/id/9071112-L.jpg",
      "https://covers.openlibrary.org/b/id/10971114-L.jpg",
      "https://covers.openlibrary.org/b/id/13133768-L.jpg",
      "https://covers.openlibrary.org/b/id/8231980-L.jpg",
      "https://covers.openlibrary.org/b/id/2627261-L.jpg",
      "https://covers.openlibrary.org/b/id/8330137-L.jpg",
      "https://covers.openlibrary.org/b/id/794451-L.jpg",
      "https://covers.openlibrary.org/b/id/14654048-L.jpg",
      "https://covers.openlibrary.org/b/id/7210841-L.jpg",
      "https://covers.openlibrary.org/b/id/12968129-L.jpg",
      "https://covers.openlibrary.org/b/id/13133765-L.jpg",
      "https://covers.openlibrary.org/b/id/368417-L.jpg",
      "https://covers.openlibrary.org/b/id/6550491-L.jpg",
      "https://covers.openlibrary.org/b/id/12951810-L.jpg",
      "https://covers.openlibrary.org/b/id/6398626-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL1238284W",
    price: 40.99,
    name: "Exercitia spiritualia",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8027976-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/9895838-L.jpg",
      "https://covers.openlibrary.org/b/id/13802249-L.jpg",
      "https://covers.openlibrary.org/b/id/9958315-L.jpg",
      "https://covers.openlibrary.org/b/id/9307105-L.jpg",
      "https://covers.openlibrary.org/b/id/5642961-L.jpg",
      "https://covers.openlibrary.org/b/id/10070539-L.jpg",
      "https://covers.openlibrary.org/b/id/9721947-L.jpg",
      "https://covers.openlibrary.org/b/id/15067971-L.jpg",
      "https://covers.openlibrary.org/b/id/3862423-L.jpg",
      "https://covers.openlibrary.org/b/id/10073658-L.jpg",
      "https://covers.openlibrary.org/b/id/4712970-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL58235W",
    price: 42.99,
    name: "Management information systems",
    description:
      "Laudon’s essential case-based text for the study of IS in business today.\r\nManagement Information Systems: Managing the Digital Firm provides the most comprehensive overview of information systems, while drawing connections between MIS and business performance. The Laudons are known for their outstanding real-world case studies, which describe how well-known companies use IT to solve problems and achieve business objectives. You will develop sought-after skills, and be adept at leading IS-related management discussions and using IT to meet bottom-line results. Each chapter of the 17th edition has been thoroughly updated to cover the latest industry and technology changes.",
    cover: "https://covers.openlibrary.org/b/id/1104118-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/8775000-L.jpg",
      "https://covers.openlibrary.org/b/id/8765345-L.jpg",
      "https://covers.openlibrary.org/b/id/4957496-L.jpg",
      "https://covers.openlibrary.org/b/id/8768777-L.jpg",
      "https://covers.openlibrary.org/b/id/12417083-L.jpg",
      "https://covers.openlibrary.org/b/id/4570525-L.jpg",
      "https://covers.openlibrary.org/b/id/1109272-L.jpg",
      "https://covers.openlibrary.org/b/id/10302756-L.jpg",
      "https://covers.openlibrary.org/b/id/9427071-L.jpg",
      "https://covers.openlibrary.org/b/id/4569653-L.jpg",
      "https://covers.openlibrary.org/b/id/4958232-L.jpg",
      "https://covers.openlibrary.org/b/id/8510655-L.jpg",
      "https://covers.openlibrary.org/b/id/10203562-L.jpg",
      "https://covers.openlibrary.org/b/id/14851627-L.jpg",
      "https://covers.openlibrary.org/b/id/14551162-L.jpg",
      "https://covers.openlibrary.org/b/id/1112163-L.jpg",
      "https://covers.openlibrary.org/b/id/9410901-L.jpg",
      "https://covers.openlibrary.org/b/id/14551161-L.jpg",
      "https://covers.openlibrary.org/b/id/1112018-L.jpg",
      "https://covers.openlibrary.org/b/id/14550935-L.jpg",
      "https://covers.openlibrary.org/b/id/10499965-L.jpg",
      "https://covers.openlibrary.org/b/id/5032575-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL17732W",
    price: 45.99,
    name: "Bible",
    description:
      "A Christian Bible is a set of books divided into the Old and New Testament that a Christian denomination has, at some point in their past or present, regarded as divinely inspired scripture.",
    cover: "https://covers.openlibrary.org/b/id/12707846-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/204879-L.jpg",
      "https://covers.openlibrary.org/b/id/206338-L.jpg",
      "https://covers.openlibrary.org/b/id/15166981-L.jpg",
      "https://covers.openlibrary.org/b/id/7724134-L.jpg",
      "https://covers.openlibrary.org/b/id/13326281-L.jpg",
      "https://covers.openlibrary.org/b/id/1955152-L.jpg",
      "https://covers.openlibrary.org/b/id/127553-L.jpg",
      "https://covers.openlibrary.org/b/id/1955143-L.jpg",
      "https://covers.openlibrary.org/b/id/201759-L.jpg",
      "https://covers.openlibrary.org/b/id/7847119-L.jpg",
      "https://covers.openlibrary.org/b/id/637900-L.jpg",
      "https://covers.openlibrary.org/b/id/2942742-L.jpg",
      "https://covers.openlibrary.org/b/id/2942743-L.jpg",
      "https://covers.openlibrary.org/b/id/14981454-L.jpg",
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/15171354-L.jpg",
      "https://covers.openlibrary.org/b/id/2394886-L.jpg",
      "https://covers.openlibrary.org/b/id/1955153-L.jpg",
      "https://covers.openlibrary.org/b/id/15166998-L.jpg",
      "https://covers.openlibrary.org/b/id/7468450-L.jpg",
      "https://covers.openlibrary.org/b/id/2400510-L.jpg",
      "https://covers.openlibrary.org/b/id/1879765-L.jpg",
      "https://covers.openlibrary.org/b/id/7611492-L.jpg",
      "https://covers.openlibrary.org/b/id/7724075-L.jpg",
      "https://covers.openlibrary.org/b/id/2329954-L.jpg",
      "https://covers.openlibrary.org/b/id/2402830-L.jpg",
      "https://covers.openlibrary.org/b/id/14500545-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL259026W",
    price: 20.99,
    name: "King Lear",
    description:
      "King Lear divides his kingdom among the two daughters who flatter him and banishes the third one who loves him. His eldest daughters both then reject him at their homes, so Lear goes mad and wanders through a storm. His banished daughter returns with an army, but they lose the battle and Lear, all his daughters and more, die.\r\n\r\n([source][1])\r\n\r\n\r\n  [1]: https://www.shakespeare.org.uk/explore-shakespeare/shakespedia/shakespeares-plays/king-lear/",
    cover: "https://covers.openlibrary.org/b/id/7420452-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/15131344-L.jpg",
      "https://covers.openlibrary.org/b/id/14065312-L.jpg",
      "https://covers.openlibrary.org/b/id/14065313-L.jpg",
      "https://covers.openlibrary.org/b/id/15081777-L.jpg",
      "https://covers.openlibrary.org/b/id/14042065-L.jpg",
      "https://covers.openlibrary.org/b/id/14996824-L.jpg",
      "https://covers.openlibrary.org/b/id/13563519-L.jpg",
      "https://covers.openlibrary.org/b/id/15120065-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL1140109W",
    price: 24.99,
    name: "The Good Earth",
    description:
      "This tells the poignant tale of a Chinese farmer and his family in old agrarian China. The humble Wang Lung glories in the soil he works, nurturing the land as it nurtures him and his family. Nearby, the nobles of the House of Hwang consider themselves above the land and its workers; but they will soon meet their own downfall.\r\n\r\nHard times come upon Wang Lung and his family when flood and drought force them to seek work in the city. The working people riot, breaking into the homes of the rich and forcing them to flee. When Wang Lung shows mercy to one noble and is rewarded, he begins to rise in the world, even as the House of Hwang falls.",
    cover: "https://covers.openlibrary.org/b/id/2626823-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/14971110-L.jpg",
      "https://covers.openlibrary.org/b/id/14471050-L.jpg",
      "https://covers.openlibrary.org/b/id/14971103-L.jpg",
      "https://covers.openlibrary.org/b/id/8236695-L.jpg",
      "https://covers.openlibrary.org/b/id/14945571-L.jpg",
      "https://covers.openlibrary.org/b/id/13533484-L.jpg",
      "https://covers.openlibrary.org/b/id/8609157-L.jpg",
      "https://covers.openlibrary.org/b/id/10020842-L.jpg",
      "https://covers.openlibrary.org/b/id/14971111-L.jpg",
      "https://covers.openlibrary.org/b/id/4650117-L.jpg",
      "https://covers.openlibrary.org/b/id/7271579-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL258902W",
    price: 36.99,
    name: "Macbeth",
    description:
      'The play concerns a trusted general who secretly lusts for power. Encouraged by the prophecies of three witches and urged on by his ambitious wife Macbeth commits regicide. Left fearful and superstitious by this desperate act he is driven to a spiralling course of murder and outrage, almost inevitably culminating in his own death. One of Shakespeare’s most popular tragedies, Macbeth is ostensibly based on the Scottish king although the story represented in the play bears no relation to historical fact as the true King Macbeth was well respected by his contemporaries. This book includes the hero Macbeth becoming more and more evil after he gets told his "destiny" by the witches and becomes greedy with power.',
    cover: "https://covers.openlibrary.org/b/id/872432-L.jpg",
    covers: [],
    comments: [],
  },
  {
    id: "OL58402W",
    price: 38.99,
    name: "Guess How Much I Love You",
    description:
      "Welcome the family classic with an elegant, refreshed cover — the quintessential picture book, just waiting to be shared.\r\n\r\nSometimes, when you love someone very, very much, you want to find a way of describing how much you treasure them. But, as Little Nutbrown Hare and Big Nutbrown Hare discover, love is not an easy thing to measure! For two decades, Sam McBratney’s timelessly endearing story, beautifully rendered in Anita Jeram’s exquisite watercolors, has captured the deep and tender bond between parent and child. Guess How Much I Love You is one of the world’s best-loved picture books.",
    cover: "https://covers.openlibrary.org/b/id/13282906-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/9139947-L.jpg",
      "https://covers.openlibrary.org/b/id/2272391-L.jpg",
      "https://covers.openlibrary.org/b/id/7777653-L.jpg",
      "https://covers.openlibrary.org/b/id/11321873-L.jpg",
      "https://covers.openlibrary.org/b/id/516519-L.jpg",
      "https://covers.openlibrary.org/b/id/10030691-L.jpg",
      "https://covers.openlibrary.org/b/id/516821-L.jpg",
      "https://covers.openlibrary.org/b/id/10331711-L.jpg",
      "https://covers.openlibrary.org/b/id/10314398-L.jpg",
      "https://covers.openlibrary.org/b/id/12963524-L.jpg",
      "https://covers.openlibrary.org/b/id/516600-L.jpg",
      "https://covers.openlibrary.org/b/id/9827611-L.jpg",
      "https://covers.openlibrary.org/b/id/9076266-L.jpg",
      "https://covers.openlibrary.org/b/id/11456506-L.jpg",
      "https://covers.openlibrary.org/b/id/10093002-L.jpg",
      "https://covers.openlibrary.org/b/id/10104834-L.jpg",
      "https://covers.openlibrary.org/b/id/8672354-L.jpg",
      "https://covers.openlibrary.org/b/id/14657904-L.jpg",
      "https://covers.openlibrary.org/b/id/13849214-L.jpg",
      "https://covers.openlibrary.org/b/id/9374880-L.jpg",
      "https://covers.openlibrary.org/b/id/516028-L.jpg",
      "https://covers.openlibrary.org/b/id/8327473-L.jpg",
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/10080667-L.jpg",
      "https://covers.openlibrary.org/b/id/8469772-L.jpg",
      "https://covers.openlibrary.org/b/id/482226-L.jpg",
      "https://covers.openlibrary.org/b/id/14855780-L.jpg",
      "https://covers.openlibrary.org/b/id/9397595-L.jpg",
      "https://covers.openlibrary.org/b/id/11456508-L.jpg",
      "https://covers.openlibrary.org/b/id/10093624-L.jpg",
      "https://covers.openlibrary.org/b/id/11456505-L.jpg",
      "https://covers.openlibrary.org/b/id/14658149-L.jpg",
      "https://covers.openlibrary.org/b/id/9374991-L.jpg",
      "https://covers.openlibrary.org/b/id/7773517-L.jpg",
      "https://covers.openlibrary.org/b/id/14657902-L.jpg",
      "https://covers.openlibrary.org/b/id/9404280-L.jpg",
      "https://covers.openlibrary.org/b/id/516235-L.jpg",
      "https://covers.openlibrary.org/b/id/516361-L.jpg",
      "https://covers.openlibrary.org/b/id/9079996-L.jpg",
      "https://covers.openlibrary.org/b/id/11456507-L.jpg",
      "https://covers.openlibrary.org/b/id/10100415-L.jpg",
      "https://covers.openlibrary.org/b/id/8585540-L.jpg",
      "https://covers.openlibrary.org/b/id/10326231-L.jpg",
      "https://covers.openlibrary.org/b/id/12629477-L.jpg",
      "https://covers.openlibrary.org/b/id/2613158-L.jpg",
      "https://covers.openlibrary.org/b/id/11456509-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL93082W",
    price: 21.99,
    name: "La Divina Commedia",
    description:
      "De goddelijke komedie is de beschrijving van een denkbeeldige tocht door het hiernamaals. Zij heeft drie delen: de hel, het vagevuur en het paradijs en ieder van deze delen heeft drieëndertig zangen van niet geheel gelijke lengte, terwijl aan het eerste deel nog een inleidende zang voorafgaat, waardoor het totale aantal van de zang honderd bedraagt. Dit aantal is geen toevalligheid. Het getal honderd gold in de middeleeuwse getallensymboliek, waarvan ook Dante een naarstig beoefenaar was, als het zinnebeeld van de volmaaktheid. Drie is het getal van de personen der heilige drie-eenheid, drieëndertig is het aantal jaren van Jezus' aardse leven. \r\n\r\nIn de eerste zang van De goddelijke komedie is Dante verdwaald in een donker woud en terwijl hij wanhopig naar hulp uitziet ontmoet hij daar de Latijnse dichter Vergilius. Samen verlaten zij het aardoppervlak en dalen af naar de hel, die voorgesteld wordt als een systeem van concentrische, zich steeds verder vernauwende kringen, een soort geringde trechter, die tenslotte in het middelpunt van de aarde eindigt. Daar zit Lucifer in het ijs, met zijn hoofd naar ons halfrond toe en met zijn voeten naar het zuidelijk halfrond gekeerd. \r\n\r\nTussen het ijs en Lucifer vinden Dante en Vergilius een weg langs het middelpunt van de aarde en stijgen dan weer op naar het zuidelijk halfrond. Zij bereiken een eiland, waar zich een hoge berg verheft, de louteringsberg van het vagevuur, waar de zielen die in staat van genade zijn gestorven, maar hun aardse schulden nog niet hebben uitgeboet, geleidelijk gelouterd worden en opstijgen naar de hemelse zaligheid. Deze berg, een soort tegenbeeld van de hel, heeft langs zijn flanken steeds nauwer wordende gaanderijen. Daarlangs stijgen Dante en Vergilius opwaarts naar de top, waar zich het aardse paradijs bevindt. \r\n\r\nWanneer zij daar zijn aangekomen, wordt Vergilius als Dante's geleider afgelost door Beatrice. Samen met Beatrice stijgt Dante nu opwaarts naar het paradijs. De eeuwige woonplaats van de zaligen bestraald door het licht van God.",
    cover: "https://covers.openlibrary.org/b/id/11621024-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/7239629-L.jpg",
      "https://covers.openlibrary.org/b/id/13474401-L.jpg",
      "https://covers.openlibrary.org/b/id/8246134-L.jpg",
      "https://covers.openlibrary.org/b/id/7183506-L.jpg",
      "https://covers.openlibrary.org/b/id/8252950-L.jpg",
      "https://covers.openlibrary.org/b/id/15170417-L.jpg",
      "https://covers.openlibrary.org/b/id/15154629-L.jpg",
      "https://covers.openlibrary.org/b/id/14551103-L.jpg",
      "https://covers.openlibrary.org/b/id/15162608-L.jpg",
      "https://covers.openlibrary.org/b/id/8246135-L.jpg",
      "https://covers.openlibrary.org/b/id/7183508-L.jpg",
      "https://covers.openlibrary.org/b/id/13962173-L.jpg",
      "https://covers.openlibrary.org/b/id/13766342-L.jpg",
      "https://covers.openlibrary.org/b/id/6458366-L.jpg",
      "https://covers.openlibrary.org/b/id/6783109-L.jpg",
      "https://covers.openlibrary.org/b/id/6032287-L.jpg",
      "https://covers.openlibrary.org/b/id/13474402-L.jpg",
      "https://covers.openlibrary.org/b/id/13962167-L.jpg",
      "https://covers.openlibrary.org/b/id/8252949-L.jpg",
      "https://covers.openlibrary.org/b/id/13474400-L.jpg",
      "https://covers.openlibrary.org/b/id/6032299-L.jpg",
      "https://covers.openlibrary.org/b/id/9711949-L.jpg",
      "https://covers.openlibrary.org/b/id/13474399-L.jpg",
      "https://covers.openlibrary.org/b/id/12460037-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL166894W",
    price: 43.99,
    name: "Преступление и наказание",
    description:
      "From [wikipedia][1]:\r\n\r\nCrime and Punishment (Russian: Преступлéние и наказáние, tr. Prestupleniye i nakazaniye; IPA: [prʲɪstʊˈplʲenʲə ɪ nəkɐˈzanʲə]) is a novel by the Russian author Fyodor Dostoyevsky. It was first published in the literary journal The Russian Messenger in twelve monthly installments during 1866.[1] It was later published in a single volume. It is the second of Dostoyevsky's full-length novels following his return from ten years of exile in Siberia. Crime and Punishment is considered the first great novel of his \"mature\" period of writing.[2]\r\n\r\nCrime and Punishment focuses on the mental anguish and moral dilemmas of Rodion Raskolnikov, an impoverished ex-student in St. Petersburg who formulates and executes a plan to kill an unscrupulous pawnbroker for her cash. Raskolnikov argues that with the pawnbroker's money he can perform good deeds to counterbalance the crime, while ridding the world of a worthless vermin. He also commits this murder to test his own hypothesis that some people are naturally capable of such things, and even have the right to do them. Several times throughout the novel, Raskolnikov justifies his actions by comparing himself with Napoleon Bonaparte, believing that murder is permissible in pursuit of a higher purpose.\r\n\r\n\r\n----------\r\nSee also: \r\n\r\n - [Преступлéние и наказáние: 1/2](https://openlibrary.org/works/OL7998899W/Prestuplenie_i_nakazanie._1_2)\r\n\r\n  [1]: https://en.wikipedia.org/wiki/Crime_and_Punishment",
    cover: "https://covers.openlibrary.org/b/id/9411873-L.jpg",
    covers: [],
    comments: [],
  },
  {
    id: "OL362698W",
    price: 20.99,
    name: "As You Like It",
    description:
      "This play has two principal settings: the court that Frederick has usurped from his brother, the rightful Duke, and the Forest of Arden, where the Duke and his followers (including the disgruntled Lord Jaques and the jester Touchstone) are living.",
    cover: "https://covers.openlibrary.org/b/id/7338874-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/10871778-L.jpg",
      "https://covers.openlibrary.org/b/id/11250700-L.jpg",
      "https://covers.openlibrary.org/b/id/11069795-L.jpg",
      "https://covers.openlibrary.org/b/id/10223888-L.jpg",
      "https://covers.openlibrary.org/b/id/10871756-L.jpg",
      "https://covers.openlibrary.org/b/id/10868543-L.jpg",
      "https://covers.openlibrary.org/b/id/6869291-L.jpg",
      "https://covers.openlibrary.org/b/id/10861717-L.jpg",
      "https://covers.openlibrary.org/b/id/10905591-L.jpg",
      "https://covers.openlibrary.org/b/id/10916857-L.jpg",
      "https://covers.openlibrary.org/b/id/6866698-L.jpg",
      "https://covers.openlibrary.org/b/id/10861523-L.jpg",
      "https://covers.openlibrary.org/b/id/10860804-L.jpg",
      "https://covers.openlibrary.org/b/id/10863428-L.jpg",
      "https://covers.openlibrary.org/b/id/11428224-L.jpg",
      "https://covers.openlibrary.org/b/id/13725703-L.jpg",
      "https://covers.openlibrary.org/b/id/10848248-L.jpg",
      "https://covers.openlibrary.org/b/id/10867697-L.jpg",
      "https://covers.openlibrary.org/b/id/10861778-L.jpg",
      "https://covers.openlibrary.org/b/id/10719815-L.jpg",
      "https://covers.openlibrary.org/b/id/10867735-L.jpg",
      "https://covers.openlibrary.org/b/id/10865487-L.jpg",
      "https://covers.openlibrary.org/b/id/11233779-L.jpg",
      "https://covers.openlibrary.org/b/id/12034423-L.jpg",
      "https://covers.openlibrary.org/b/id/10541101-L.jpg",
      "https://covers.openlibrary.org/b/id/10731042-L.jpg",
      "https://covers.openlibrary.org/b/id/10917702-L.jpg",
      "https://covers.openlibrary.org/b/id/10862536-L.jpg",
      "https://covers.openlibrary.org/b/id/10880065-L.jpg",
      "https://covers.openlibrary.org/b/id/10879472-L.jpg",
      "https://covers.openlibrary.org/b/id/10860904-L.jpg",
      "https://covers.openlibrary.org/b/id/10731044-L.jpg",
      "https://covers.openlibrary.org/b/id/10863761-L.jpg",
      "https://covers.openlibrary.org/b/id/10874485-L.jpg",
      "https://covers.openlibrary.org/b/id/11736609-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL15155002W",
    price: 50.99,
    name: "The Ugly Duckling",
    description:
      "An ugly and unloved duckling turns out to be a beautiful swan.",
    cover: "https://covers.openlibrary.org/b/id/446546-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/8912787-L.jpg",
      "https://covers.openlibrary.org/b/id/12371155-L.jpg",
      "https://covers.openlibrary.org/b/id/5264743-L.jpg",
      "https://covers.openlibrary.org/b/id/6040311-L.jpg",
      "https://covers.openlibrary.org/b/id/7482553-L.jpg",
      "https://covers.openlibrary.org/b/id/9125549-L.jpg",
      "https://covers.openlibrary.org/b/id/6443600-L.jpg",
      "https://covers.openlibrary.org/b/id/11353031-L.jpg",
      "https://covers.openlibrary.org/b/id/10547640-L.jpg",
      "https://covers.openlibrary.org/b/id/8912832-L.jpg",
      "https://covers.openlibrary.org/b/id/15034834-L.jpg",
      "https://covers.openlibrary.org/b/id/1357897-L.jpg",
      "https://covers.openlibrary.org/b/id/9149793-L.jpg",
      "https://covers.openlibrary.org/b/id/5268026-L.jpg",
      "https://covers.openlibrary.org/b/id/1255541-L.jpg",
      "https://covers.openlibrary.org/b/id/3351060-L.jpg",
      "https://covers.openlibrary.org/b/id/1357964-L.jpg",
      "https://covers.openlibrary.org/b/id/3351144-L.jpg",
      "https://covers.openlibrary.org/b/id/12504826-L.jpg",
      "https://covers.openlibrary.org/b/id/2590356-L.jpg",
      "https://covers.openlibrary.org/b/id/12981560-L.jpg",
      "https://covers.openlibrary.org/b/id/12098528-L.jpg",
      "https://covers.openlibrary.org/b/id/3334585-L.jpg",
      "https://covers.openlibrary.org/b/id/11980629-L.jpg",
      "https://covers.openlibrary.org/b/id/8912590-L.jpg",
      "https://covers.openlibrary.org/b/id/12163465-L.jpg",
      "https://covers.openlibrary.org/b/id/10325921-L.jpg",
      "https://covers.openlibrary.org/b/id/2271689-L.jpg",
      "https://covers.openlibrary.org/b/id/1288920-L.jpg",
      "https://covers.openlibrary.org/b/id/2685236-L.jpg",
      "https://covers.openlibrary.org/b/id/10994978-L.jpg",
      "https://covers.openlibrary.org/b/id/7355803-L.jpg",
      "https://covers.openlibrary.org/b/id/8913196-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL1073898W",
    price: 12.99,
    name: "The Story of Philosophy",
    description:
      "Includes chapters on Plato, Aristotle, Francis Bacon, Spinoza, Voltaire, Kant, and Nietzsche.",
    cover: "https://covers.openlibrary.org/b/id/405360-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/3183143-L.jpg",
      "https://covers.openlibrary.org/b/id/14912217-L.jpg",
      "https://covers.openlibrary.org/b/id/15070498-L.jpg",
      "https://covers.openlibrary.org/b/id/15070518-L.jpg",
      "https://covers.openlibrary.org/b/id/14914316-L.jpg",
      "https://covers.openlibrary.org/b/id/14920778-L.jpg",
      "https://covers.openlibrary.org/b/id/15070491-L.jpg",
      "https://covers.openlibrary.org/b/id/15070487-L.jpg",
      "https://covers.openlibrary.org/b/id/14913139-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL258850W",
    price: 41.99,
    name: "Othello",
    description:
      "Shakespeare's tragedy of jealousy and suspicion presented scene by scene in comic book format.",
    cover: "https://covers.openlibrary.org/b/id/7165018-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/12754676-L.jpg",
      "https://covers.openlibrary.org/b/id/11427259-L.jpg",
      "https://covers.openlibrary.org/b/id/10917506-L.jpg",
      "https://covers.openlibrary.org/b/id/12007058-L.jpg",
      "https://covers.openlibrary.org/b/id/12043517-L.jpg",
      "https://covers.openlibrary.org/b/id/14041639-L.jpg",
      "https://covers.openlibrary.org/b/id/12373121-L.jpg",
      "https://covers.openlibrary.org/b/id/10842690-L.jpg",
      "https://covers.openlibrary.org/b/id/11416473-L.jpg",
      "https://covers.openlibrary.org/b/id/12034533-L.jpg",
      "https://covers.openlibrary.org/b/id/12386673-L.jpg",
      "https://covers.openlibrary.org/b/id/12197957-L.jpg",
      "https://covers.openlibrary.org/b/id/12034607-L.jpg",
      "https://covers.openlibrary.org/b/id/10815045-L.jpg",
      "https://covers.openlibrary.org/b/id/13916760-L.jpg",
      "https://covers.openlibrary.org/b/id/11263751-L.jpg",
      "https://covers.openlibrary.org/b/id/12043445-L.jpg",
      "https://covers.openlibrary.org/b/id/10631550-L.jpg",
      "https://covers.openlibrary.org/b/id/14368382-L.jpg",
      "https://covers.openlibrary.org/b/id/11223008-L.jpg",
      "https://covers.openlibrary.org/b/id/11427612-L.jpg",
      "https://covers.openlibrary.org/b/id/11427301-L.jpg",
      "https://covers.openlibrary.org/b/id/12034749-L.jpg",
      "https://covers.openlibrary.org/b/id/10226531-L.jpg",
      "https://covers.openlibrary.org/b/id/14041640-L.jpg",
      "https://covers.openlibrary.org/b/id/14368381-L.jpg",
      "https://covers.openlibrary.org/b/id/10689229-L.jpg",
      "https://covers.openlibrary.org/b/id/10668283-L.jpg",
      "https://covers.openlibrary.org/b/id/11310080-L.jpg",
      "https://covers.openlibrary.org/b/id/11175625-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL5840870W",
    price: 36.99,
    name: "The Boy in the Striped Pyjamas",
    description:
      "The Boy in the Striped Pyjamas is a 2006 Holocaust novel by Irish novelist John Boyne.",
    cover: "https://covers.openlibrary.org/b/id/12720687-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/9359747-L.jpg",
      "https://covers.openlibrary.org/b/id/10497103-L.jpg",
      "https://covers.openlibrary.org/b/id/14609006-L.jpg",
      "https://covers.openlibrary.org/b/id/13926350-L.jpg",
      "https://covers.openlibrary.org/b/id/8461731-L.jpg",
      "https://covers.openlibrary.org/b/id/12370368-L.jpg",
      "https://covers.openlibrary.org/b/id/14351304-L.jpg",
      "https://covers.openlibrary.org/b/id/12370574-L.jpg",
      "https://covers.openlibrary.org/b/id/8930965-L.jpg",
      "https://covers.openlibrary.org/b/id/15133576-L.jpg",
      "https://covers.openlibrary.org/b/id/14411192-L.jpg",
      "https://covers.openlibrary.org/b/id/12817091-L.jpg",
      "https://covers.openlibrary.org/b/id/12869871-L.jpg",
      "https://covers.openlibrary.org/b/id/13772063-L.jpg",
      "https://covers.openlibrary.org/b/id/13696868-L.jpg",
      "https://covers.openlibrary.org/b/id/15142579-L.jpg",
      "https://covers.openlibrary.org/b/id/14827484-L.jpg",
      "https://covers.openlibrary.org/b/id/9356936-L.jpg",
      "https://covers.openlibrary.org/b/id/14201566-L.jpg",
      "https://covers.openlibrary.org/b/id/13527179-L.jpg",
      "https://covers.openlibrary.org/b/id/12249970-L.jpg",
      "https://covers.openlibrary.org/b/id/14131057-L.jpg",
      "https://covers.openlibrary.org/b/id/14131056-L.jpg",
      "https://covers.openlibrary.org/b/id/14423666-L.jpg",
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/12855912-L.jpg",
      "https://covers.openlibrary.org/b/id/14827486-L.jpg",
      "https://covers.openlibrary.org/b/id/14541813-L.jpg",
      "https://covers.openlibrary.org/b/id/14827514-L.jpg",
      "https://covers.openlibrary.org/b/id/14411188-L.jpg",
      "https://covers.openlibrary.org/b/id/13777399-L.jpg",
      "https://covers.openlibrary.org/b/id/14201565-L.jpg",
      "https://covers.openlibrary.org/b/id/12359425-L.jpg",
      "https://covers.openlibrary.org/b/id/10183002-L.jpg",
      "https://covers.openlibrary.org/b/id/13777383-L.jpg",
      "https://covers.openlibrary.org/b/id/14201568-L.jpg",
      "https://covers.openlibrary.org/b/id/14201567-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL8721462W",
    price: 27.99,
    name: "Great Expectations",
    description:
      "Great Expectations is the thirteenth novel by Charles Dickens and his penultimate completed novel. It depicts the education of an orphan nicknamed Pip (the book is a bildungsroman; a coming-of-age story). It is Dickens' second novel, after David Copperfield, to be fully narrated in the first person. The novel was first published as a serial in Dickens's weekly periodical All the Year Round, from 1 December 1860 to August 1861. In October 1861, Chapman and Hall published the novel in three volumes.\r\n\r\nThe novel is set in Kent and London in the early to mid-19th century and contains some of Dickens's most celebrated scenes, starting in a graveyard, where the young Pip is accosted by the escaped convict Abel Magwitch. Great Expectations is full of extreme imagery – poverty, prison ships and chains, and fights to the death – and has a colourful cast of characters who have entered popular culture. These include the eccentric Miss Havisham, the beautiful but cold Estella, and Joe, the unsophisticated and kind blacksmith. Dickens's themes include wealth and poverty, love and rejection, and the eventual triumph of good over evil. Great Expectations, which is popular both with readers and literary critics, has been translated into many languages and adapted numerous times into various media.",
    cover: "https://covers.openlibrary.org/b/id/13322313-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/12295274-L.jpg",
      "https://covers.openlibrary.org/b/id/12353117-L.jpg",
      "https://covers.openlibrary.org/b/id/12269066-L.jpg",
      "https://covers.openlibrary.org/b/id/12253682-L.jpg",
      "https://covers.openlibrary.org/b/id/12242118-L.jpg",
      "https://covers.openlibrary.org/b/id/12260509-L.jpg",
      "https://covers.openlibrary.org/b/id/12120245-L.jpg",
      "https://covers.openlibrary.org/b/id/12296456-L.jpg",
      "https://covers.openlibrary.org/b/id/12320356-L.jpg",
      "https://covers.openlibrary.org/b/id/14972728-L.jpg",
      "https://covers.openlibrary.org/b/id/12129317-L.jpg",
      "https://covers.openlibrary.org/b/id/12215771-L.jpg",
      "https://covers.openlibrary.org/b/id/12233033-L.jpg",
      "https://covers.openlibrary.org/b/id/14972723-L.jpg",
      "https://covers.openlibrary.org/b/id/12216540-L.jpg",
      "https://covers.openlibrary.org/b/id/12281080-L.jpg",
      "https://covers.openlibrary.org/b/id/10849057-L.jpg",
      "https://covers.openlibrary.org/b/id/12272076-L.jpg",
      "https://covers.openlibrary.org/b/id/14972747-L.jpg",
      "https://covers.openlibrary.org/b/id/12109249-L.jpg",
      "https://covers.openlibrary.org/b/id/12253308-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL10396878W",
    price: 21.99,
    name: "Laws, etc",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/5810161-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/4588188-L.jpg",
      "https://covers.openlibrary.org/b/id/3830544-L.jpg",
      "https://covers.openlibrary.org/b/id/5382088-L.jpg",
      "https://covers.openlibrary.org/b/id/6558157-L.jpg",
      "https://covers.openlibrary.org/b/id/6075868-L.jpg",
      "https://covers.openlibrary.org/b/id/5809050-L.jpg",
      "https://covers.openlibrary.org/b/id/5802866-L.jpg",
      "https://covers.openlibrary.org/b/id/5380453-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL23205W",
    price: 45.99,
    name: "The Grapes of Wrath",
    description:
      "Steinbeck’s classic novel of the Great Depression is as vivid now as ever. The story focuses on a family of Oklahoma sharecroppers, farmers who work another man’s land for a share of the crops. Driven from their home by drought and poverty they take to the road in a battered old truck and make their way to California to look for work. When they arrive they find hundreds of others like them being forced to work for breadline wages. they begin working as fruit pickers, strike-breakers replacing the people who have been trying to establish a union but their consciences force them to leave.",
    cover: "https://covers.openlibrary.org/b/id/12715902-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/11228113-L.jpg",
      "https://covers.openlibrary.org/b/id/13008630-L.jpg",
      "https://covers.openlibrary.org/b/id/15003492-L.jpg",
      "https://covers.openlibrary.org/b/id/7368021-L.jpg",
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/12295233-L.jpg",
      "https://covers.openlibrary.org/b/id/15125606-L.jpg",
      "https://covers.openlibrary.org/b/id/14914275-L.jpg",
      "https://covers.openlibrary.org/b/id/13008606-L.jpg",
      "https://covers.openlibrary.org/b/id/14896020-L.jpg",
      "https://covers.openlibrary.org/b/id/13008610-L.jpg",
      "https://covers.openlibrary.org/b/id/14424059-L.jpg",
      "https://covers.openlibrary.org/b/id/14972286-L.jpg",
      "https://covers.openlibrary.org/b/id/8770722-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL76524W",
    price: 28.99,
    name: "The Thirty-Nine Steps",
    description:
      "Richard Hannay has just returned to England after years in South Africa and is thoroughly bored with his life in London.  But then a murder is committed in his flat, just days after a chance encounter with an American who had told him about an assassination plot which could have dire international consequences.  An obvious suspect for the police and an easy target for the killers, Hannay goes on the run in his native Scotland where he will need all his courage and ingenuity to stay one step ahead of his pursuers.",
    cover: "https://covers.openlibrary.org/b/id/93020-L.jpg",
    covers: [],
    comments: [],
  },
  {
    id: "OL5735363W",
    price: 32.99,
    name: "The Hunger Games",
    description:
      "The Hunger Games is a 2008 dystopian novel by the American writer Suzanne Collins. It is written in the perspective of 16-year-old Katniss Everdeen, who lives in the future, post-apocalyptic nation of Panem in North America. The Capitol, a highly advanced metropolis, exercises political control over the rest of the nation. The Hunger Games is an annual event in which one boy and one girl aged 12–18 from each of the twelve districts surrounding the Capitol are selected by lottery to compete in a televised battle royale to the death.\r\n\r\nThe book received critical acclaim from major reviewers and authors. It was praised for its plot and character development. In writing The Hunger Games, Collins drew upon Greek mythology, Roman gladiatorial games, and contemporary reality television for thematic content. The novel won many awards, including the California Young Reader Medal, and was named one of Publishers Weekly's \"Best Books of the Year\" in 2008.\r\n\r\nThe Hunger Games was first published in hardcover on September 14, 2008, by Scholastic, featuring a cover designed by Tim O'Brien.",
    cover: "https://covers.openlibrary.org/b/id/12646537-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/15111703-L.jpg",
      "https://covers.openlibrary.org/b/id/13570772-L.jpg",
      "https://covers.openlibrary.org/b/id/13526322-L.jpg",
      "https://covers.openlibrary.org/b/id/15168582-L.jpg",
      "https://covers.openlibrary.org/b/id/15167336-L.jpg",
      "https://covers.openlibrary.org/b/id/15139410-L.jpg",
      "https://covers.openlibrary.org/b/id/13944877-L.jpg",
      "https://covers.openlibrary.org/b/id/13766461-L.jpg",
      "https://covers.openlibrary.org/b/id/14855536-L.jpg",
      "https://covers.openlibrary.org/b/id/14855544-L.jpg",
      "https://covers.openlibrary.org/b/id/13188964-L.jpg",
      "https://covers.openlibrary.org/b/id/14855537-L.jpg",
      "https://covers.openlibrary.org/b/id/15168023-L.jpg",
      "https://covers.openlibrary.org/b/id/15167828-L.jpg",
      "https://covers.openlibrary.org/b/id/15167646-L.jpg",
      "https://covers.openlibrary.org/b/id/15168460-L.jpg",
      "https://covers.openlibrary.org/b/id/15111704-L.jpg",
      "https://covers.openlibrary.org/b/id/14635829-L.jpg",
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/14131021-L.jpg",
      "https://covers.openlibrary.org/b/id/13575602-L.jpg",
      "https://covers.openlibrary.org/b/id/14564960-L.jpg",
      "https://covers.openlibrary.org/b/id/14819483-L.jpg",
      "https://covers.openlibrary.org/b/id/15168030-L.jpg",
      "https://covers.openlibrary.org/b/id/15168021-L.jpg",
      "https://covers.openlibrary.org/b/id/14131022-L.jpg",
      "https://covers.openlibrary.org/b/id/15168586-L.jpg",
      "https://covers.openlibrary.org/b/id/15167826-L.jpg",
      "https://covers.openlibrary.org/b/id/15168492-L.jpg",
      "https://covers.openlibrary.org/b/id/14846995-L.jpg",
      "https://covers.openlibrary.org/b/id/13941003-L.jpg",
      "https://covers.openlibrary.org/b/id/14844157-L.jpg",
      "https://covers.openlibrary.org/b/id/15168022-L.jpg",
      "https://covers.openlibrary.org/b/id/15168028-L.jpg",
      "https://covers.openlibrary.org/b/id/15120650-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL362702W",
    price: 42.99,
    name: "Julius Caesar",
    description:
      "Presents the original text of Shakespeare's play side by side with a modern version, discusses the author and the theater of his time, and provides quizzes and other study activities.",
    cover: "https://covers.openlibrary.org/b/id/7901303-L.jpg",
    covers: [],
    comments: [],
  },
  {
    id: "OL17773390W",
    price: 33.99,
    name: "Practical JavaScript programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/3854378-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/3854378-L.jpg"],
    comments: [],
  },
  {
    id: "OL25632028W",
    price: 45.99,
    name: "Javascript Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/14483955-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/14483955-L.jpg"],
    comments: [],
  },
  {
    id: "OL21867740W",
    price: 20.99,
    name: "JavaScript Programming Pattern",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/13886516-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/13886516-L.jpg"],
    comments: [],
  },

  {
    id: "OL25520448W",
    price: 32.99,
    name: "Javascript",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/13789638-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/13789638-L.jpg"],
    comments: [],
  },

  {
    id: "OL15444205W",
    price: 29.99,
    name: "Eloquent Javascript",
    description:
      '"*Eloquent JavaScript* is a book providing an introduction to the JavaScript programming language and programming in general."',
    cover: "https://covers.openlibrary.org/b/id/7082166-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/14820601-L.jpg",
      "https://covers.openlibrary.org/b/id/7199153-L.jpg",
      "https://covers.openlibrary.org/b/id/8644134-L.jpg",
      "https://covers.openlibrary.org/b/id/12995869-L.jpg",
      "https://covers.openlibrary.org/b/id/8508178-L.jpg",
      "https://covers.openlibrary.org/b/id/10601909-L.jpg",
      "https://covers.openlibrary.org/b/id/8513405-L.jpg",
    ],
    comments: [],
  },

  {
    id: "OL2692465W",
    price: 12.99,
    name: "Learn advanced JavaScript programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/1874138-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/1874138-L.jpg"],
    comments: [],
  },
  {
    id: "OL1643770W",
    price: 22.99,
    name: "JavaScript",
    description:
      "JavaScript is a powerful, object-based scripting language; JavaScript programs can be embedded directly into HTML web pages. When combined with the Document Object Model (DOM) defined by a web browser, JavaScript allows you to create Dynamic HTML (DHTML) content and interactive client-side web applications. JavaScript syntax is based on the popular programming languages C, C++, and Java, which makes it familiar and easy to learn for experienced programmers. At the same time, JavaScript is an interpreted scripting language, providing a flexible, forgiving environment in which new programmers can learn.\r\n\r\n*JavaScript: The Definitive Guide* provides a thorough description of the core JavaScript language and both the legacy and standard DOMs implemented in web browsers. The book includes sophisticated examples that show you how to handle common tasks such as validating form data, working with cookies, and creating portable DHTML animations. The book also contains detailed reference sections that cover the core JavaScript API, the legacy client-side API, and the W3C standard DOM API, documenting every JavaScript object, method, property, constructor, constant, function, and event handler in those APIs.\r\n\r\nThis fourth edition of the bestselling JavaScript book has been carefully updated to cover JavaScript 1.5 (ECMAScript Version 3). The book also provides complete coverage of the W3C DOM standard (Level 1 and Level 2), while retaining material on the legacy Level 0 DOM for backward compatibility.\r\n\r\n*JavaScript: The Definitive Guide* is a complete programmer's guide and reference manual for JavaScript. It is particularly useful for developers working with the latest standards-compliant web browsers, such as Internet Explorer 6, Netscape 6, and Mozilla. HTML authors can learn how to use JavaScript to build dynamic web pages. Experienced programmers can quickly find the information they need to start writing sophisticated JavaScript programs. This book is an indispensable reference for all JavaScript programmers, regardless of experience level.\r\n\r\n----------\r\n*Description from the Fourth Edition (2007, O'Reilly Media)*\r\n\r\n<h2>Printing History</h2>\r\n<dl> \r\n<dt>August 1996</dt>\r\n<dd>Beta Edition.</dd>\r\n<dt>January 1997</dt>\r\n<dd>Second Edition.</dd> \r\n<dt>June 1998</dt>\r\n<dd>Third Edition.</dd> \r\n<dt>January 2002</dt>\r\n<dd>Fourth Edition.</dd> \r\n</dl>",
    cover: "https://covers.openlibrary.org/b/id/10737959-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/805641-L.jpg",
      "https://covers.openlibrary.org/b/id/14488181-L.jpg",
      "https://covers.openlibrary.org/b/id/6519345-L.jpg",
      "https://covers.openlibrary.org/b/id/14562317-L.jpg",
      "https://covers.openlibrary.org/b/id/-1-L.jpg",
      "https://covers.openlibrary.org/b/id/10229384-L.jpg",
      "https://covers.openlibrary.org/b/id/10737969-L.jpg",
      "https://covers.openlibrary.org/b/id/15087914-L.jpg",
      "https://covers.openlibrary.org/b/id/988222-L.jpg",
      "https://covers.openlibrary.org/b/id/10737959-L.jpg",
      "https://covers.openlibrary.org/b/id/10738025-L.jpg",
      "https://covers.openlibrary.org/b/id/805759-L.jpg",
      "https://covers.openlibrary.org/b/id/13955143-L.jpg",
      "https://covers.openlibrary.org/b/id/10738098-L.jpg",
      "https://covers.openlibrary.org/b/id/13955144-L.jpg",
      "https://covers.openlibrary.org/b/id/388464-L.jpg",
      "https://covers.openlibrary.org/b/id/10738063-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL8221266W",
    price: 26.99,
    name: "HTML & JavaScript",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/365269-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/365269-L.jpg",
      "https://covers.openlibrary.org/b/id/13091091-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL24807285W",
    price: 27.99,
    name: "JAVASCRIPT",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/11575841-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/11575841-L.jpg"],
    comments: [],
  },
  {
    id: "OL1820616W",
    price: 12.99,
    name: "Java and JavaScript programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/1100750-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/1100750-L.jpg"],
    comments: [],
  },
  {
    id: "OL13614569W",
    price: 40.99,
    name: "The JavaScript programming language",
    description:
      '"The JavaScript Programming Language provides a brief introduction to the JavaScript language that is now an important component of every programmer\'s tool box. This helpful guide offers an overview of JavaScript to students interested in pursuing advanced programming skills and delving into web development." "Clear and concise, The JavaScript Programming Language is an excellent primer to this popular dynamic language and is ideal for use on its own or when coupled with one of Jones and Bartlett\'s outstanding introductory computer science texts"--Book jacket.',
    cover: "https://covers.openlibrary.org/b/id/12191848-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/12191848-L.jpg"],
    comments: [],
  },

  {
    id: "OL19546617W",
    price: 41.99,
    name: "Javascript: Beginners Guide on Javascript Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8512669-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/8512669-L.jpg"],
    comments: [],
  },

  {
    id: "OL114676W",
    price: 10.99,
    name: "Introduction to Java Programming",
    description:
      "For courses in Java - Introduction to Programming and Object-Oriented Programming, this fifth edition is revised and expanded to include more extensive coverage of advanced Java topics. Early chapters guide students through simple examples and exercises.Subsequent chapters progressively present Java programming in detail.",
    cover: "https://covers.openlibrary.org/b/id/85920-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/85920-L.jpg",
      "https://covers.openlibrary.org/b/id/13097152-L.jpg",
      "https://covers.openlibrary.org/b/id/82465-L.jpg",
      "https://covers.openlibrary.org/b/id/841053-L.jpg",
      "https://covers.openlibrary.org/b/id/89462-L.jpg",
      "https://covers.openlibrary.org/b/id/82464-L.jpg",
      "https://covers.openlibrary.org/b/id/89461-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL3503668W",
    price: 27.99,
    name: "Java Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/5406811-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/4813741-L.jpg",
      "https://covers.openlibrary.org/b/id/4640811-L.jpg",
      "https://covers.openlibrary.org/b/id/14847889-L.jpg",
      "https://covers.openlibrary.org/b/id/5406811-L.jpg",
    ],
    comments: [],
  },

  {
    id: "OL6223299W",
    price: 20.99,
    name: "Effective Java",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/1176573-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/2334826-L.jpg",
      "https://covers.openlibrary.org/b/id/134335-L.jpg",
      "https://covers.openlibrary.org/b/id/8509606-L.jpg",
      "https://covers.openlibrary.org/b/id/12420356-L.jpg",
      "https://covers.openlibrary.org/b/id/7429009-L.jpg",
      "https://covers.openlibrary.org/b/id/9348726-L.jpg",
      "https://covers.openlibrary.org/b/id/9911458-L.jpg",
      "https://covers.openlibrary.org/b/id/1176573-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL16988753W",
    price: 20.99,
    name: "Java programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/9430172-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/9430172-L.jpg"],
    comments: [],
  },
  {
    id: "OL29571480W",
    price: 36.99,
    name: "Java Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/13164331-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/13164331-L.jpg"],
    comments: [],
  },
  {
    id: "OL449055W",
    price: 36.99,
    name: "Big Java",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/1239523-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/1239523-L.jpg",
      "https://covers.openlibrary.org/b/id/304392-L.jpg",
      "https://covers.openlibrary.org/b/id/6382989-L.jpg",
      "https://covers.openlibrary.org/b/id/306377-L.jpg",
    ],
    comments: [],
  },

  {
    id: "OL8492268W",
    price: 48.99,
    name: "Java Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/506676-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/506676-L.jpg"],
    comments: [],
  },
  {
    id: "OL3233590W",
    price: 15.99,
    name: "Java Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/252868-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/252869-L.jpg",
      "https://covers.openlibrary.org/b/id/252868-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL22705232W",
    price: 48.99,
    name: "Programming with Java",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/10487733-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/14859622-L.jpg",
      "https://covers.openlibrary.org/b/id/10487733-L.jpg",
      "https://covers.openlibrary.org/b/id/10557761-L.jpg",
      "https://covers.openlibrary.org/b/id/13707897-L.jpg",
      "https://covers.openlibrary.org/b/id/10599410-L.jpg",
      "https://covers.openlibrary.org/b/id/10557760-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL11987899W",
    price: 27.99,
    name: "Java programming",
    description:
      '"This book was written for C++ programmers to learn the Java programming language using JDK 1.1. You can leverage your C++ skills to quickly develop Java skills to at least the level of Certified Java Programmer as defined by the Sun certification program.".\n\n"This book moves from the basics of the Java language to the essential and powerful programming techniques supported by the Java language, including extending existing classes, implementing interfaces, exception handling, multithreading, cloning objects, run-time type information, and advanced language constructs such as inner classes. This book gives overviews of the packages provided by the Java platform.\n\nThe classes in these packages support stream I/O and random-access file I/O, networking, collection classes, programming graphical user interfaces for applications, creating applets, and internationalizing programs. A chapter on JavaBeans - reusable software components that can be input directly into an ever-growing number of rapid application development (RAD) tools - is also included."--BOOK JACKET.',
    cover: "https://covers.openlibrary.org/b/id/1421552-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/9830071-L.jpg",
      "https://covers.openlibrary.org/b/id/1421552-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL23868245W",
    price: 23.99,
    name: "Java program design",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/5005860-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/5005860-L.jpg"],
    comments: [],
  },

  {
    id: "OL15959929W",
    price: 23.99,
    name: "Introduction to JAVA programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/9435785-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/9435785-L.jpg"],
    comments: [],
  },
  {
    id: "OL16961757W",
    price: 10.99,
    name: "Introduction to JAVA programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/9537991-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/9537991-L.jpg"],
    comments: [],
  },
  {
    id: "OL16509491W",
    price: 25.99,
    name: "Introduction to Java programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/8665105-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/8665105-L.jpg"],
    comments: [],
  },
  {
    id: "OL5974397W",
    price: 48.99,
    name: "Java programming with Oracle JDBC",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/388485-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/388485-L.jpg"],
    comments: [],
  },
  {
    id: "OL2863751W",
    price: 49.99,
    name: "KickAss Java Programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/2083449-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/2083449-L.jpg",
      "https://covers.openlibrary.org/b/id/2083448-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL16342737W",
    price: 26.99,
    name: "Java programming",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/13162223-L.jpg",
    covers: ["https://covers.openlibrary.org/b/id/13162223-L.jpg"],
    comments: [],
  },
  {
    id: "OL2734879W",
    price: 29.99,
    name: "The Java programming language",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/135609-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/135872-L.jpg",
      "https://covers.openlibrary.org/b/id/134336-L.jpg",
      "https://covers.openlibrary.org/b/id/135609-L.jpg",
      "https://covers.openlibrary.org/b/id/8359411-L.jpg",
    ],
    comments: [],
  },
  {
    id: "OL18996549W",
    price: 46.99,
    name: "Java Program Design",
    description: "",
    cover: "https://covers.openlibrary.org/b/id/64961-L.jpg",
    covers: [
      "https://covers.openlibrary.org/b/id/64960-L.jpg",
      "https://covers.openlibrary.org/b/id/64961-L.jpg",
    ],
    comments: [],
  },
];

export const getBooks = async () => {
  await delay(500);
  return booksDB;
};
