import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

import { Nav } from "../components/layout/Nav";
import { GetCurrentUserAction } from "@/actions/authActions";
import { UserProvider } from "@/context/UserContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /*   const currentUser = await GetCurrentUserAction(); */

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        {children}
        {/*         <UserProvider initialUser={currentUser}>
          <div className="h-screen grid grid-cols-[6rem_1fr] gap-9 pr-10 pl-1 relative">
            <Nav />
            <div className="h-full overflow-hidden ">{children}</div>
          </div>
        </UserProvider> */}
      </body>
    </html>
  );
}
